apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sample-web
spec:
  selector:
    matchLabels:
      app: sample-web
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sample-web
    spec:
      containers:
      - name: webapp
        image: pbskr/sampleapp:v1
        ports:
        - containerPort: 80
